[package]
name = "tracktorio"
version = "0.1.0"
edition = "2021"

[dependencies]
geng.git = "https://github.com/geng-engine/geng"
noisy_float = "0.2.0"
pathfinding = "4.14.0"
serde = { version = "1.0.219", features = ["derive"] }
