background = "#222"

[fov]
default = 20
min = 10
max = 100

[track]
width = 1
color = "#aaa"

[drawing]
preview_color = "#aaa7"

[control]
target_window_height = 100
min_drag_distance = 5
zoom_speed = 1.01
drag_timer = 0.5
snap_distance = 10
